# -*- coding: utf-8 -*-
"""BreastCancerDetection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hhf_q7dvmYGMNvYp1cqY_OMv-Gt6gJV5
"""

import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
cancer_data=load_breast_cancer()
print(cancer_data.keys())

print(cancer_data['DESCR'])

cancer_data['data'].shape

df=pd.DataFrame(cancer_data['data'],columns=cancer_data['feature_names'])
print(df)

cancer_data['target'].shape

cancer_data['target_names']

df['target']=cancer_data['target']
print(df.head())

X=df[cancer_data.feature_names].values
y=df['target'].values

model=LogisticRegression(solver='liblinear')

model.fit(X,y)
model.predict([X[0]])
model.score(X,y)